name: update-repo-docs

on:
  workflow_dispatch:
  schedule:
    - cron: '5 4 * * *'
  push:
    branches:
      - main

permissions:
  read-all

jobs:
  update-repo-docs:
    permissions:
      contents: write
      pull-requests: write
    uses: fortify/shared-doc-resources/.github/workflows/update-repo-docs.yml@main
